name: Python CI Workflow

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image for the CI

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python (choose your version)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Use the version of Python you prefer

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests using unittest
      - name: Run tests
        run: |
          python -m unittest discover -s tests  # Discover tests in 'tests' folder
